/**
 * Deterministic generator for the Digital Music Stand E2E fixture score.
 *
 * WHY THIS EXISTS
 * ---------------
 * `prisma/seed.ts` creates the MusicPiece + MusicFile row the stand E2E specs
 * read, but the stand viewer streams the PDF through
 * `/api/stand/files/<storageKey>` and rasterises it with PDF.js. A row without a
 * real file on disk renders the "Sheet music files are unavailable" state, and a
 * file with no ink renders a correctly-sized but fully transparent canvas — which
 * the specs deliberately treat as a failure (`painted > 1000` non-transparent
 * pixels). So the fixture needs a genuine, inked, multi-page PDF.
 *
 * WHY IT IS GENERATED AND NOT COMMITTED
 * -------------------------------------
 * A committed binary blob cannot be reviewed. This script builds the exact same
 * bytes from readable drawing instructions, so the fixture's contents are
 * auditable in a diff: five-line staves, barlines, note heads with stems, and a
 * page title on every page.
 *
 * DETERMINISM
 * -----------
 * pdf-lib stamps CreationDate/ModDate from `new Date()` unless told otherwise,
 * which would make every run produce different bytes and defeat "is this fixture
 * already up to date?" checks. Both dates are pinned to EPOCH below, so
 * `buildStandE2EFixturePdf()` is byte-for-byte reproducible.
 *
 * Usage:
 *   npx tsx scripts/generate-stand-e2e-fixture-pdf.ts            # write to stdout path
 *   npx tsx scripts/generate-stand-e2e-fixture-pdf.ts out.pdf    # write to out.pdf
 */
import { writeFileSync } from 'node:fs';

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';

/** Letter, matching a real concert part so the stand's canvas sizing is realistic. */
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;

const MARGIN_LEFT = 72;
const MARGIN_RIGHT = 540;

/** Fixed timestamp so the generated bytes never change between runs. */
const FIXED_DATE = new Date('2024-01-01T00:00:00.000Z');

/** Must match `STAND_E2E_FIXTURE_PAGE_COUNT` in prisma/seed.ts. */
export const STAND_E2E_FIXTURE_PAGE_COUNT = 27;

const TITLE = 'Fanfare for Testing';
const COMPOSER = 'Deterministic Fixture Composer';

/** Five-line staff: five evenly spaced horizontal rules. */
const STAFF_LINE_COUNT = 5;
const STAFF_LINE_GAP = 12;
/** Vertical distance between the top line of one staff and the next. */
const STAFF_SYSTEM_GAP = 78;

function drawStaff(page: PDFPage, topY: number): void {
  for (let line = 0; line < STAFF_LINE_COUNT; line++) {
    const y = topY - line * STAFF_LINE_GAP;
    page.drawLine({
      start: { x: MARGIN_LEFT, y },
      end: { x: MARGIN_RIGHT, y },
      thickness: 1,
      color: rgb(0, 0, 0),
    });
  }
}

function drawBarlines(page: PDFPage, topY: number, barCount: number): void {
  const staffHeight = (STAFF_LINE_COUNT - 1) * STAFF_LINE_GAP;
  const usableWidth = MARGIN_RIGHT - MARGIN_LEFT;
  for (let bar = 0; bar <= barCount; bar++) {
    const x = MARGIN_LEFT + (usableWidth * bar) / barCount;
    page.drawLine({
      start: { x, y: topY },
      end: { x, y: topY - staffHeight },
      thickness: bar % 4 === 0 ? 1.6 : 0.8,
      color: rgb(0, 0, 0),
    });
  }
}

/** A filled note head plus its stem — the ink that proves a real rasterisation. */
function drawNote(page: PDFPage, x: number, y: number, up: boolean): void {
  page.drawEllipse({
    x,
    y,
    xScale: 4.6,
    yScale: 3.4,
    color: rgb(0, 0, 0),
  });
  page.drawLine({
    start: { x: x + 4.4, y },
    end: { x: x + 4.4, y: up ? y + 26 : y - 26 },
    thickness: 1.1,
    color: rgb(0, 0, 0),
  });
}

/**
 * Build the fixture score: `pageCount` pages, each with a title, a subtitle and
 * four notated staves.
 */
export async function buildStandE2EFixturePdf(
  pageCount: number = STAND_E2E_FIXTURE_PAGE_COUNT,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(TITLE);
  doc.setAuthor(COMPOSER);
  doc.setProducer('eccb-stand-e2e-fixture-generator');
  doc.setCreator('scripts/generate-stand-e2e-fixture-pdf.ts');
  doc.setCreationDate(FIXED_DATE);
  doc.setModificationDate(FIXED_DATE);

  const bold: PDFFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular: PDFFont = await doc.embedFont(StandardFonts.Helvetica);

  for (let index = 0; index < pageCount; index++) {
    const pageNumber = index + 1;
    const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

    page.drawText(TITLE, {
      x: MARGIN_LEFT,
      y: PAGE_HEIGHT - 90,
      size: 22,
      font: bold,
      color: rgb(0.05, 0.2, 0.35),
    });
    page.drawText(`${COMPOSER} - page ${pageNumber} of ${pageCount}`, {
      x: MARGIN_LEFT,
      y: PAGE_HEIGHT - 118,
      size: 14,
      font: regular,
      color: rgb(0, 0, 0),
    });

    // Four systems down the page, each a five-line staff with notes on it.
    for (let system = 0; system < 4; system++) {
      const topY = PAGE_HEIGHT - 190 - system * STAFF_SYSTEM_GAP;
      drawStaff(page, topY);
      drawBarlines(page, topY, 4);

      for (let note = 0; note < 8; note++) {
        const usableWidth = MARGIN_RIGHT - MARGIN_LEFT;
        const x = MARGIN_LEFT + 24 + note * (usableWidth - 40) / 8;
        // Deterministic pseudo-random staff position; no Math.random anywhere,
        // so two runs on two machines produce identical bytes.
        const step = ((note * 3 + system * 2 + pageNumber) % STAFF_LINE_COUNT);
        const y = topY - step * STAFF_LINE_GAP;
        drawNote(page, x, y, (note + system) % 2 === 0);
      }
    }

    page.drawText(`Page ${pageNumber}`, {
      x: PAGE_WIDTH / 2 - 24,
      y: 48,
      size: 12,
      font: regular,
      color: rgb(0, 0, 0),
    });
  }

  // `useObjectStreams: false` keeps the output plain enough to eyeball in a diff
  // of hex dumps, and is what the watermark stamper also uses.
  return doc.save({ useObjectStreams: false });
}

/** CLI entry point: write the fixture to the given path (default: storage key). */
async function main(): Promise<void> {
  const target =
    process.argv[2] ?? 'storage/music/e2e-stand-fixture/e2e-stand-fixture.pdf';
  const bytes = await buildStandE2EFixturePdf();
  writeFileSync(target, bytes);
  console.log(
    `Wrote ${bytes.length} bytes, ${STAND_E2E_FIXTURE_PAGE_COUNT} pages to ${target}`,
  );
}

// Only run as a script; importing this module (as prisma/seed.ts does) must not
// write files as a side effect.
if (process.argv[1]?.endsWith('generate-stand-e2e-fixture-pdf.ts')) {
  main().catch((error) => {
    console.error('Failed to generate the stand E2E fixture PDF:', error);
    process.exit(1);
  });
}
